language: cpp
#cache: ccache 

git:
  depth: 1

branches:
  except:
    - /^Last_.*/

dist:
    bionic

addons:
  apt:
    packages:
      - build-essential
      - libtool
      - make
      - cmake
      - libboost1.65-dev
      - libboost-system1.65-dev
      - libboost-program-options1.65-dev
      - libboost-thread1.65-dev
      - libboost-regex1.65-dev
      - wget

install:
  # Install newer cmake
#   - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
#   - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
#   - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.16.2/cmake-3.16.2-Linux-x86_64.tar.gz
#   - tar -xvf cmake-3.16.2-Linux-x86_64.tar.gz > /dev/null
#   - mv cmake-3.16.2-Linux-x86_64 cmake-install
#   - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
#   - cd ${TRAVIS_BUILD_DIR}

matrix:
  include:
    - os: linux
      arch: arm64
      compiler: gcc
      env:
        - CC=gcc-7
        - CXX=g++-7

script: |-
  cmake --version
  wget https://raw.githubusercontent.com/ToShukKr/mangos-classic-raspberry-pi/master/MangosPI.patch -O arm.patch ; patch -p1 < arm.patch
  mkdir _build
  mkdir _install
  cd _build
  export CCACHE_SLOPPINESS=pch_defines,time_macros
  cmake -DCMAKE_INSTALL_PREFIX=../_install -DBUILD_EXTRACTORS=ON -DBUILD_AHBOT=ON -DBUILD_PLAYERBOT=ON ..
  make -j2
  make install
